export const NAV_LINKS = [
  { href: "#about", label: "Profile" },
  { href: "#work", label: "Work" },
  { href: "#arsenal", label: "Capabilities" },
  { href: "#experience", label: "Journey" },
  { href: "#contact", label: "Contact" },
] as const;

export const HERO_ROLES = [
  "Graphic Designer & Video Editor",
  "Brand & Visual Designer",
  "Visual Designer & Content Creator",
] as const;

export const HERO_PROOF_POINTS = [
  { value: "4+", label: "Brand design, video editing & UI" },
  { value: "100+", label: "Projects across print, digital & motion" },
] as const;

export type ProjectType = "image" | "video";

export type ProjectCategory =
  | "All Works"
  | "Cinematic"
  | "Brand Identity"
  | "Digital & UI"
  | "Print Design"
  | "Campaign Design";

export interface ProjectVisualTreatment {
  code: string;
  signal: string;
  texture: string;
  tint: string;
  frame: string;
}

export interface ShowcaseProject {
  id: number;
  title: string;
  category: Exclude<ProjectCategory, "All Works">;
  gradient: string;
  accent: string;
  tags: readonly string[];
  summary: string;
  outcome: string;
  type: ProjectType;
  videoSrc?: string;
  imgSrc?: string;
  bentoSize: "large" | "medium";
  brief: string;
  deliverables: readonly string[];
  impact: string;
  role: string;
  mediaAlt: string;
  visualTreatment: ProjectVisualTreatment;
}

export const PROJECT_CATEGORIES: readonly ProjectCategory[] = [
  "All Works",
  "Cinematic",
  "Brand Identity",
  "Digital & UI",
  "Print Design",
  "Campaign Design",
] as const;

export const SHOWCASE_PROJECTS: readonly ShowcaseProject[] = [
  {
    id: 1,
    title: "Coastal Cravings Street Identity",
    category: "Brand Identity",
    gradient: "from-violet-500/20 via-zinc-950/40 to-transparent",
    accent: "#9F7AEA",
    tags: ["Logo Design", "Brand System"],
    summary: "Premium brand language for a modern dining experience.",
    outcome: "Built a recognizable identity kit from logo design to mockup.",
    type: "image",
    imgSrc: "/works/Logo/Logo mockup.png",
    bentoSize: "large",
    brief: "Create a confident visual system that feels premium and appetizing.",
    deliverables: ["Logo direction", "Brand marks", "Mockups"],
    impact: "Established a clear, recognizable brand presence.",
    role: "Brand identity, logo design",
    mediaAlt: "Coastal Cravings signage logo mockup",
    visualTreatment: {
      code: "SYS-01",
      signal: "Identity Mockup",
      texture: "vellum grid",
      tint: "rgba(159, 122, 234, 0.34)",
      frame: "01",
    },
  },
  {
    id: 2,
    title: "Coastal Cravings Signature Mark",
    category: "Brand Identity",
    gradient: "from-fuchsia-500/20 via-zinc-950/40 to-transparent",
    accent: "#D946EF",
    tags: ["Logo Design", "Vector Art"],
    summary: "Primary full-color logo mark for Coastal Cravings.",
    outcome: "Clean, scalable vector logo for versatile applications.",
    type: "image",
    imgSrc: "/works/Logo/Coastal Cravings Logo.png",
    bentoSize: "large",
    brief: "Develop a scalable, instantly recognizable restaurant logo.",
    deliverables: ["Vector Logo", "Color Palette"],
    impact: "Provided a strong primary identifier for the brand.",
    role: "Logo Design",
    mediaAlt: "Coastal Cravings Logo Full Color",
    visualTreatment: {
      code: "SYS-02",
      signal: "Primary Mark",
      texture: "clean vector",
      tint: "rgba(217, 70, 239, 0.28)",
      frame: "02",
    },
  },
  {
    id: 4,
    title: "Cinematic Final Output",
    category: "Cinematic",
    gradient: "from-indigo-500/20 via-zinc-950/40 to-transparent",
    accent: "#818CF8",
    tags: ["Premiere Pro", "Video Editing"],
    summary: "Edits built around pacing, mood, and narrative recall.",
    outcome: "Sharper visual storyboard and dynamic final reel.",
    type: "video",
    videoSrc: "/works/Videos/Final Output.mp4",
    bentoSize: "medium",
    brief: "Shape footage into a concise, premium rhythm.",
    deliverables: ["Edit structure", "Motion graphics", "Final render"],
    impact: "Translated motion decisions into a strong narrative reel.",
    role: "Video editing, motion direction",
    mediaAlt: "Cinematic Video Reel",
    visualTreatment: {
      code: "CIN-01",
      signal: "Narrative Pacing",
      texture: "film grain",
      tint: "rgba(129, 140, 248, 0.32)",
      frame: "16:9",
    },
  },
  {
    id: 5,
    title: "Restaurant Menu Layout",
    category: "Print Design",
    gradient: "from-amber-500/20 via-zinc-950/40 to-transparent",
    accent: "#F59E0B",
    tags: ["Print Layout", "Typography"],
    summary: "Clear and structured layout for physical menu prints.",
    outcome: "Clarified reading flow and dish hierarchy.",
    type: "image",
    imgSrc: "/works/Menu card/Menu Card Mockup.jpg",
    bentoSize: "large",
    brief: "Design a print-ready menu with reduced friction.",
    deliverables: ["Menu Layout", "Typography", "Print Mockup"],
    impact: "Converted complex menus into a scannable experience.",
    role: "Layout design, print setup",
    mediaAlt: "Menu Card Mockup",
    visualTreatment: {
      code: "PRT-01",
      signal: "Print System",
      texture: "paper grain",
      tint: "rgba(245, 158, 11, 0.28)",
      frame: "A5",
    },
  },
  {
    id: 6,
    title: "A5 Menu Print File",
    category: "Print Design",
    gradient: "from-orange-500/20 via-zinc-950/40 to-transparent",
    accent: "#F97316",
    tags: ["Production", "Print Layout"],
    summary: "Production-ready A5 file for the restaurant menu.",
    outcome: "Delivered precise margins and bleed for commercial printing.",
    type: "image",
    imgSrc: "/works/Menu card/A5 Menu card.jpg",
    bentoSize: "medium",
    brief: "Finalize the menu layout for professional offset printing.",
    deliverables: ["A5 Layout", "CMYK Setup", "Print files"],
    impact: "Ensured zero-error transition from screen to print.",
    role: "Production Artist",
    mediaAlt: "A5 Menu Card Flat",
    visualTreatment: {
      code: "PRT-02",
      signal: "Production File",
      texture: "print marks",
      tint: "rgba(249, 115, 22, 0.28)",
      frame: "A5",
    },
  },
  {
    id: 7,
    title: "GreenMonk Gourmet Launch Poster",
    category: "Campaign Design",
    gradient: "from-cyan-500/20 via-zinc-950/40 to-transparent",
    accent: "#22D3EE",
    tags: ["Photoshop", "Compositing"],
    summary: "High-impact visual posters designed for product campaigns.",
    outcome: "Strengthened product storytelling with striking visuals.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Posters/output in mockup.jpg",
    bentoSize: "medium",
    brief: "Create posters that hook immediately and showcase the product.",
    deliverables: ["Visual concept", "Compositing", "Mockups"],
    impact: "Gave campaign assets a premium focal point.",
    role: "Visual direction, compositing",
    mediaAlt: "Product Poster Mockup",
    visualTreatment: {
      code: "CMP-01",
      signal: "Launch Visual",
      texture: "poster paper",
      tint: "rgba(34, 211, 238, 0.24)",
      frame: "A4",
    },
  },
  {
    id: 8,
    title: "Coastal Table Campaign Poster",
    category: "Campaign Design",
    gradient: "from-sky-500/20 via-zinc-950/40 to-transparent",
    accent: "#0EA5E9",
    tags: ["Layout", "Typography"],
    summary: "The flat A4 layout design of the product campaign poster.",
    outcome: "Detailed typography and hierarchy rules established.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Posters/A4_1.jpg",
    bentoSize: "medium",
    brief: "Design the core typographical hierarchy for the product poster.",
    deliverables: ["A4 Layout", "Typography", "Visual balance"],
    impact: "Created a scalable poster layout for multiple products.",
    role: "Layout design",
    mediaAlt: "A4 Product Poster Flat",
    visualTreatment: {
      code: "CMP-02",
      signal: "Flat Layout",
      texture: "clean digital",
      tint: "rgba(14, 165, 233, 0.24)",
      frame: "A4",
    },
  },
  {
    id: 9,
    title: "Kalyan Skyline Billboard",
    category: "Campaign Design",
    gradient: "from-teal-500/20 via-zinc-950/40 to-transparent",
    accent: "#14B8A6",
    tags: ["OOH", "Large Format"],
    summary: "Large format outdoor billboard design for Kalyan Events.",
    outcome: "High visibility and legible typography at scale.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/KE bill board.jpg",
    bentoSize: "medium",
    brief: "Design an eye-catching billboard that communicates the event instantly.",
    deliverables: ["Billboard layout", "Large format typography"],
    impact: "Drove significant local awareness for the event series.",
    role: "OOH Layout Design",
    mediaAlt: "Kalyan Events Billboard",
    visualTreatment: {
      code: "OOH-01",
      signal: "Large Scale",
      texture: "vinyl print",
      tint: "rgba(20, 184, 166, 0.24)",
      frame: "WIDE",
    },
  },
  {
    id: 10,
    title: "Dolly May Spotlight Poster",
    category: "Campaign Design",
    gradient: "from-emerald-500/20 via-zinc-950/40 to-transparent",
    accent: "#10B981",
    tags: ["Visual Design", "Poster"],
    summary: "Dynamic poster series for focused promotional bursts.",
    outcome: "Raised campaign polish with cleaner, bolder frames.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/poster 1.jpg",
    bentoSize: "medium",
    brief: "Refine visual material for production-ready promotional pieces.",
    deliverables: ["Poster design", "Visual polish"],
    impact: "Improved visual communication for the brand.",
    role: "Visual design, layout",
    mediaAlt: "Promotional Poster 1",
    visualTreatment: {
      code: "VIS-01",
      signal: "Promo Frame 1",
      texture: "matte finish",
      tint: "rgba(16, 185, 129, 0.24)",
      frame: "POSTER",
    },
  },
  {
    id: 11,
    title: "After Party Neon Flyer",
    category: "Campaign Design",
    gradient: "from-emerald-400/20 via-zinc-950/40 to-transparent",
    accent: "#34D399",
    tags: ["Visual Design", "Poster"],
    summary: "Second variant in the dynamic promotional poster series.",
    outcome: "Expanded the visual vocabulary of the campaign.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/poster 2.jpg",
    bentoSize: "medium",
    brief: "Create an alternate visual direction for A/B testing.",
    deliverables: ["Alternate Poster", "Color iteration"],
    impact: "Provided clients with diverse aesthetic options.",
    role: "Visual design",
    mediaAlt: "Promotional Poster 2",
    visualTreatment: {
      code: "VIS-02",
      signal: "Promo Frame 2",
      texture: "matte finish",
      tint: "rgba(52, 211, 153, 0.24)",
      frame: "POSTER",
    },
  },
  {
    id: 12,
    title: "Live Stage Energy Poster",
    category: "Campaign Design",
    gradient: "from-green-500/20 via-zinc-950/40 to-transparent",
    accent: "#22C55E",
    tags: ["Visual Design", "Poster"],
    summary: "Third variant showcasing alternate typography and layout.",
    outcome: "Delivered a comprehensive suite of promotional assets.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/poster 3.jpg",
    bentoSize: "medium",
    brief: "Explore a typographic-heavy approach for the campaign.",
    deliverables: ["Typographic Poster", "Layout grid"],
    impact: "Strengthened the campaign's flexibility across channels.",
    role: "Typography, layout",
    mediaAlt: "Promotional Poster 3",
    visualTreatment: {
      code: "VIS-03",
      signal: "Promo Frame 3",
      texture: "matte finish",
      tint: "rgba(34, 197, 94, 0.24)",
      frame: "POSTER",
    },
  },
  {
    id: 13,
    title: "GreenMonk Voltage Room Poster",
    category: "Campaign Design",
    gradient: "from-lime-500/20 via-zinc-950/40 to-transparent",
    accent: "#84CC16",
    tags: ["Visual Design", "Poster"],
    summary: "Final variant in the promotional poster exploration series.",
    outcome: "Finalized the overarching look and feel of the print campaign.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Poster 7.jpg",
    bentoSize: "medium",
    brief: "Finalize the visual direction incorporating all stakeholder feedback.",
    deliverables: ["Final Poster", "Print ready file"],
    impact: "Successfully launched the primary campaign asset.",
    role: "Visual design, finishing",
    mediaAlt: "Promotional Poster 7",
    visualTreatment: {
      code: "VIS-04",
      signal: "Promo Frame 4",
      texture: "matte finish",
      tint: "rgba(132, 204, 22, 0.24)",
      frame: "POSTER",
    },
  },
  {
    id: 14,
    title: "Digital Hoarding Design",
    category: "Digital & UI",
    gradient: "from-rose-500/20 via-zinc-950/40 to-transparent",
    accent: "#FB7185",
    tags: ["Web Banner", "OOH"],
    summary: "Scalable banner systems balancing hierarchy with brand messaging.",
    outcome: "Built ready-to-deploy banners for web and outdoor.",
    type: "image",
    imgSrc: "/works/Web banner_ Hoardings/Hoarding design.jpg",
    bentoSize: "large",
    brief: "Bring campaign content into a highly visible hoarding framework.",
    deliverables: ["Hoarding layout", "Asset delivery"],
    impact: "Maximized visibility in out-of-home and digital spaces.",
    role: "Layout design, campaign rollout",
    mediaAlt: "Hoarding Design",
    visualTreatment: {
      code: "WEB-01",
      signal: "Outdoor Visibility",
      texture: "print marks",
      tint: "rgba(251, 113, 133, 0.24)",
      frame: "WIDE",
    },
  },
  {
    id: 15,
    title: "Web Banner Variant A",
    category: "Digital & UI",
    gradient: "from-pink-500/20 via-zinc-950/40 to-transparent",
    accent: "#EC4899",
    tags: ["Digital Ads", "Web Banner"],
    summary: "Optimized web banner for direct response campaigns.",
    outcome: "High click-through rates driven by clear CTA placement.",
    type: "image",
    imgSrc: "/works/Web banner_ Hoardings/web banner_1.jpg",
    bentoSize: "large",
    brief: "Translate the hoarding design into a clickable web format.",
    deliverables: ["Digital Banner", "Responsive layout"],
    impact: "Improved digital ad performance and conversion.",
    role: "Digital Design",
    mediaAlt: "Web Banner 1",
    visualTreatment: {
      code: "WEB-02",
      signal: "Digital Display",
      texture: "pixel grid",
      tint: "rgba(236, 72, 153, 0.24)",
      frame: "BANNER",
    },
  },
  {
    id: 16,
    title: "Web Banner Variant B",
    category: "Digital & UI",
    gradient: "from-rose-400/20 via-zinc-950/40 to-transparent",
    accent: "#F43F5E",
    tags: ["Digital Ads", "Web Banner"],
    summary: "Secondary web banner layout for A/B digital testing.",
    outcome: "Provided marketing teams with diverse testing assets.",
    type: "image",
    imgSrc: "/works/Web banner_ Hoardings/web banner_2.jpg",
    bentoSize: "large",
    brief: "Create an alternate layout for digital banner testing.",
    deliverables: ["Alternate Banner", "Typography adjustments"],
    impact: "Enabled data-driven design decisions for the ad campaign.",
    role: "Digital Design",
    mediaAlt: "Web Banner 2",
    visualTreatment: {
      code: "WEB-03",
      signal: "Digital Alternate",
      texture: "pixel grid",
      tint: "rgba(244, 63, 94, 0.24)",
      frame: "BANNER",
    },
  },
  ...getAdditionalShowcaseProjects(),
] as const;

export const SKILLS = [
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "DaVinci Resolve",
  "Figma",
  "Adobe XD",
  "WIX",
  "Articulate 360",
  "Logo Design",
  "Print Design",
  "Color Theory",
] as const;

export const ABOUT_HIGHLIGHTS = [
  "4 years across graphic design, visual content creation, motion edits, and brand storytelling.",
  "Strong Adobe production stack: Photoshop, Illustrator, Premiere Pro, After Effects, and DaVinci Resolve.",
  "Design systems and prototype thinking through Figma, Adobe XD, WIX, and Articulate 360 e-learning workflows.",
] as const;

export const EXPERIENCE_ENTRIES = [
  {
    role: "Graphic Designer Intern",
    company: "Pixel Scoop Studios",
    duration: "2021 January - December",
    description:
      "Started as an intern graphic designer with Adobe Photoshop and Illustrator knowledge, while also taking care of short video edits and album videos.",
    highlight: "Design internship foundation",
    focus: ["Photoshop", "Illustrator", "Short videos", "Album videos"],
  },
  {
    role: "Graphic Designer & Content Creator",
    company: "GreenMonk Energy Drink",
    duration: "2022 Jan - 2023 Feb",
    description:
      "Worked as a graphic designer on product posters, creatives, thumbnails, and UI screens, and as a video editor for music videos, product concept shorts, and YouTube videos.",
    highlight: "Campaign content system",
    focus: ["Product posters", "Creatives", "UI screens", "YouTube videos"],
  },
  {
    role: "Graphic & Web Designer",
    company: "Buddha-CEO Quantum Foundation",
    duration: "2023 March - Present",
    description:
      "Working as a graphic designer creating flyers, brochures, standees, banners, magazines with cover pages, and books, while also handling web design updates.",
    highlight: "Graphic design and web handling",
    focus: ["Flyers", "Brochures", "Standees", "Web updates"],
  },
] as const;

function getAdditionalShowcaseProjects(): readonly ShowcaseProject[] {
  return [
  {
    id: 17,
    title: "BeSuperMind Neural Identity",
    category: "Brand Identity",
    gradient: "from-blue-500/20 via-zinc-950/40 to-transparent",
    accent: "#60A5FA",
    tags: ["Logo Design", "Brand Mark"],
    summary: "A clean identity mark built for self-development and learning spaces.",
    outcome: "Created a memorable logo asset with strong digital readability.",
    type: "image",
    imgSrc: "/works/Logo/BeSuperMind copy.jpg",
    bentoSize: "large",
    brief: "Shape a confident logo direction for a knowledge-led brand.",
    deliverables: ["Logo mark", "Digital asset", "Brand presentation"],
    impact: "Gave the brand a crisp visual identifier for online touchpoints.",
    role: "Logo design",
    mediaAlt: "BeSuperMind learning logo design",
    visualTreatment: {
      code: "SYS-04",
      signal: "Learning Brand",
      texture: "digital identity",
      tint: "rgba(96, 165, 250, 0.26)",
      frame: "04",
    },
  },
  {
    id: 18,
    title: "Brand Visit Editorial Mark",
    category: "Brand Identity",
    gradient: "from-violet-500/20 via-zinc-950/40 to-transparent",
    accent: "#A78BFA",
    tags: ["Logo Design", "Identity System"],
    summary: "A polished logo presentation for a visit and discovery-led brand.",
    outcome: "Delivered a refined mark with a premium presentation frame.",
    type: "image",
    imgSrc: "/works/Logo/Logo brand visit-01.jpg.jpeg",
    bentoSize: "large",
    brief: "Create a polished logo direction with immediate brand recognition.",
    deliverables: ["Logo system", "Presentation art", "Brand mark"],
    impact: "Improved brand recall through a cleaner visual language.",
    role: "Logo design, brand presentation",
    mediaAlt: "Brand Visit media logo presentation",
    visualTreatment: {
      code: "SYS-05",
      signal: "Logo Presentation",
      texture: "presentation board",
      tint: "rgba(167, 139, 250, 0.26)",
      frame: "05",
    },
  },
  {
    id: 19,
    title: "GK Estate Crest",
    category: "Brand Identity",
    gradient: "from-cyan-500/20 via-zinc-950/40 to-transparent",
    accent: "#67E8F9",
    tags: ["Logo Design", "Visual Identity"],
    summary: "Contemporary logo exploration with a clean, adaptable mark.",
    outcome: "Produced a versatile identity asset ready for digital use.",
    type: "image",
    imgSrc: "/works/Logo/Logo 1.jpg.jpeg",
    bentoSize: "large",
    brief: "Explore a modern visual identity with strong reproduction quality.",
    deliverables: ["Logo concept", "Identity art", "Presentation export"],
    impact: "Expanded the identity portfolio with a fresh visual direction.",
    role: "Logo design",
    mediaAlt: "GK Constructions logo identity",
    visualTreatment: {
      code: "SYS-06",
      signal: "Modern Mark",
      texture: "clean vector",
      tint: "rgba(103, 232, 249, 0.22)",
      frame: "06",
    },
  },
  {
    id: 20,
    title: "GK Mechanical Crest",
    category: "Brand Identity",
    gradient: "from-emerald-500/20 via-zinc-950/40 to-transparent",
    accent: "#6EE7B7",
    tags: ["Logo Design", "Brand Concept"],
    summary: "A second logo direction focused on simplicity and memorability.",
    outcome: "Created a refined mark suitable for brand launch materials.",
    type: "image",
    imgSrc: "/works/Logo/Logo 2.jpg.jpeg",
    bentoSize: "large",
    brief: "Develop a distinct logo option with premium brand usability.",
    deliverables: ["Logo concept", "Brand mark", "Export-ready asset"],
    impact: "Added a flexible identity direction for client presentation.",
    role: "Logo design",
    mediaAlt: "GK engineering gear logo mark",
    visualTreatment: {
      code: "SYS-07",
      signal: "Brand Concept",
      texture: "identity proof",
      tint: "rgba(110, 231, 183, 0.22)",
      frame: "07",
    },
  },
  {
    id: 21,
    title: "GK Lions Civic Emblem",
    category: "Brand Identity",
    gradient: "from-amber-500/20 via-zinc-950/40 to-transparent",
    accent: "#FBBF24",
    tags: ["Logo Design", "Brand Asset"],
    summary: "A polished logo concept designed for strong first-glance recognition.",
    outcome: "Delivered a presentation-ready mark with clean visual hierarchy.",
    type: "image",
    imgSrc: "/works/Logo/Logo 3.jpg.jpeg",
    bentoSize: "large",
    brief: "Build a recognizable logo concept for a premium brand presentation.",
    deliverables: ["Logo concept", "Presentation frame", "Brand asset"],
    impact: "Rounded out the identity showcase with a bold visual option.",
    role: "Logo design",
    mediaAlt: "GK Lions Club emblem logo",
    visualTreatment: {
      code: "SYS-08",
      signal: "Identity Asset",
      texture: "brand board",
      tint: "rgba(251, 191, 36, 0.22)",
      frame: "08",
    },
  },
  {
    id: 22,
    title: "GreenMonk Signal Poster",
    category: "Campaign Design",
    gradient: "from-cyan-400/20 via-zinc-950/40 to-transparent",
    accent: "#22D3EE",
    tags: ["Poster Design", "Campaign Art"],
    summary: "A bold product poster built around strong focal hierarchy.",
    outcome: "Extended the campaign system with a high-impact visual frame.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Poster_8-01.jpg.jpeg",
    bentoSize: "medium",
    brief: "Create a premium product poster that reads quickly and feels campaign-ready.",
    deliverables: ["Poster design", "Campaign visual", "Export-ready art"],
    impact: "Added a polished poster frame for digital and print use.",
    role: "Poster design, compositing",
    mediaAlt: "GreenMonk monogram energy poster",
    visualTreatment: {
      code: "CMP-08",
      signal: "Product Focus",
      texture: "poster finish",
      tint: "rgba(34, 211, 238, 0.22)",
      frame: "POSTER",
    },
  },
  {
    id: 23,
    title: "GreenMonk Frosted Can Poster",
    category: "Campaign Design",
    gradient: "from-sky-400/20 via-zinc-950/40 to-transparent",
    accent: "#38BDF8",
    tags: ["Poster Design", "Product Campaign"],
    summary: "A campaign poster with crisp product emphasis and strong contrast.",
    outcome: "Improved product presence with a sharper promotional layout.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Poster_31-01.jpg.jpeg",
    bentoSize: "medium",
    brief: "Build a product-first promotional frame with premium polish.",
    deliverables: ["Poster layout", "Visual polish", "Campaign export"],
    impact: "Strengthened the poster series with another production-ready asset.",
    role: "Visual design",
    mediaAlt: "GreenMonk can splash poster",
    visualTreatment: {
      code: "CMP-31",
      signal: "Product Campaign",
      texture: "digital poster",
      tint: "rgba(56, 189, 248, 0.22)",
      frame: "POSTER",
    },
  },
  {
    id: 24,
    title: "GreenMonk Smoke Can Poster",
    category: "Campaign Design",
    gradient: "from-fuchsia-500/20 via-zinc-950/40 to-transparent",
    accent: "#E879F9",
    tags: ["Poster Design", "Campaign Visual"],
    summary: "A polished poster variant with vivid campaign styling.",
    outcome: "Expanded the product poster library with a distinct visual mood.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Poster_44.jpg.jpeg",
    bentoSize: "medium",
    brief: "Design a vibrant campaign frame that keeps the product central.",
    deliverables: ["Poster design", "Campaign variant", "Final export"],
    impact: "Added visual range while keeping the campaign family cohesive.",
    role: "Poster design",
    mediaAlt: "GreenMonk smoke burst poster",
    visualTreatment: {
      code: "CMP-44",
      signal: "Campaign Variant",
      texture: "high gloss",
      tint: "rgba(232, 121, 249, 0.2)",
      frame: "POSTER",
    },
  },
  {
    id: 25,
    title: "GreenMonk Laser Strike Poster",
    category: "Campaign Design",
    gradient: "from-rose-500/20 via-zinc-950/40 to-transparent",
    accent: "#FB7185",
    tags: ["Poster Design", "Promotional Art"],
    summary: "A sharp promotional poster with strong product storytelling.",
    outcome: "Created another campaign-ready asset for multi-channel promotion.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/Poster_47.jpg.jpeg",
    bentoSize: "medium",
    brief: "Craft a memorable promotional poster with clean hierarchy.",
    deliverables: ["Promotional poster", "Visual hierarchy", "Final art"],
    impact: "Broadened the poster showcase with a polished promotional frame.",
    role: "Poster design, visual layout",
    mediaAlt: "GreenMonk lime strike poster",
    visualTreatment: {
      code: "CMP-47",
      signal: "Promo Art",
      texture: "poster gloss",
      tint: "rgba(251, 113, 133, 0.2)",
      frame: "POSTER",
    },
  },
  {
    id: 26,
    title: "GreenMonk Splash Aura Creative",
    category: "Campaign Design",
    gradient: "from-lime-500/20 via-zinc-950/40 to-transparent",
    accent: "#A3E635",
    tags: ["Social Creative", "Poster"],
    summary: "A compact campaign creative built for quick social scanning.",
    outcome: "Delivered a lightweight visual asset for social promotion.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/WhatsApp Image 2024-11-30 at 2.07.01 AM.jpeg",
    bentoSize: "medium",
    brief: "Create a fast-reading creative for social distribution.",
    deliverables: ["Social poster", "Campaign creative", "Mobile export"],
    impact: "Added a mobile-first campaign visual to the portfolio.",
    role: "Social creative design",
    mediaAlt: "GreenMonk water drop creative",
    visualTreatment: {
      code: "SOC-01",
      signal: "Social Creative",
      texture: "mobile post",
      tint: "rgba(163, 230, 53, 0.18)",
      frame: "POSTER",
    },
  },
  {
    id: 27,
    title: "GreenMonk Ice Burst Creative",
    category: "Campaign Design",
    gradient: "from-green-500/20 via-zinc-950/40 to-transparent",
    accent: "#4ADE80",
    tags: ["Social Creative", "Campaign"],
    summary: "A second social poster variant for campaign distribution.",
    outcome: "Added visual variety for quick-turn digital promotion.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/WhatsApp Image 2024-11-30 at 2.07.02 AM (2).jpeg",
    bentoSize: "medium",
    brief: "Produce a clean social creative for campaign use.",
    deliverables: ["Social poster", "Digital creative", "Export asset"],
    impact: "Expanded the campaign set with a concise social frame.",
    role: "Social creative design",
    mediaAlt: "GreenMonk snow splash creative",
    visualTreatment: {
      code: "SOC-02",
      signal: "Mobile Campaign",
      texture: "mobile post",
      tint: "rgba(74, 222, 128, 0.18)",
      frame: "POSTER",
    },
  },
  {
    id: 28,
    title: "GreenMonk Level One Gig Poster",
    category: "Campaign Design",
    gradient: "from-teal-500/20 via-zinc-950/40 to-transparent",
    accent: "#2DD4BF",
    tags: ["Social Creative", "Visual Design"],
    summary: "A third social creative with compact campaign messaging.",
    outcome: "Completed the social poster trio for campaign rollout.",
    type: "image",
    imgSrc: "/works/Posters_Product posters/WhatsApp Image 2024-11-30 at 2.07.02 AM (3).jpeg",
    bentoSize: "medium",
    brief: "Create another mobile-ready campaign visual with clear impact.",
    deliverables: ["Social poster", "Campaign art", "Mobile export"],
    impact: "Strengthened the campaign library with another social-ready asset.",
    role: "Visual design",
    mediaAlt: "GreenMonk Level One event poster",
    visualTreatment: {
      code: "SOC-03",
      signal: "Campaign Post",
      texture: "mobile post",
      tint: "rgba(45, 212, 191, 0.18)",
      frame: "POSTER",
    },
  },
  ];
}

export const TOOLS = [
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "DaVinci Resolve",
  "Figma",
  "Adobe XD",
  "WIX",
  "Articulate 360",
  "Logo Design",
  "Print Design",
  "Visual Design",
  "Color Theory",
  "E-Learning",
] as const;

export const CONTACT = {
  email: "geethakrishna.designer@gmail.com",
  phone: "+917989228383",
  socials: [
    { label: "LinkedIn", href: undefined },
    { label: "Behance", href: undefined },
    { label: "Instagram", href: undefined },
  ],
} as const;

export const SITE_META = {
  title: "Geetha Krishna | Cinematic Visual Dossier",
  description:
    "Premium visual portfolio for Geetha Krishna, a graphic designer and video editor building brand systems, cinematic edits, and digital storytelling assets.",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "https://example.com",
} as const;
